language: php
php:
  - 5.3

#  - 5.4
#  - 5.5

branches:
  except:
    - share

env:
  - DB=mysql

#  - DB=pgsql
#  - DB=sqlite

before_script:
  - composer install
  - ./tests/install_dependencies.sh
  - cd tests

#  - cd ..; git clone https://github.com/owncloud/appframework; cd contacts
#  - sudo add-apt-repository -y ppa:chris-lea/node.js
#  - sudo apt-get update
#  - sudo apt-get -y install nodejs
#  - wget https://phantomjs.googlecode.com/files/phantomjs-1.9.0-linux-x86_64.tar.bz2
#  - tar xjf phantomjs-1.9.0-linux-x86_64.tar.bz2
#  - sudo ln -s $(pwd)/phantomjs-1.9.0-linux-x86_64/bin/phantomjs /usr/bin/phantomjs

script:
  - phpunit --configuration tests/phpunit.xml
  
#&& make javascript-tests
